# Generated by Django 4.1.2 on 2022-10-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("has_cough", models.BooleanField(default=False)),
                ("cough_amt_of_days", models.IntegerField(blank=True, null=True)),
                ("cough_extra_info", models.TextField(blank=True, null=True)),
                ("has_fever", models.BooleanField(default=False)),
                ("fever_last_temp", models.FloatField(blank=True, null=True)),
                ("fever_amt_of_days", models.IntegerField(blank=True, null=True)),
                ("has_headache", models.BooleanField(default=False)),
                ("headache_severity", models.IntegerField(blank=True, null=True)),
                ("headache_amt_of_days", models.IntegerField(blank=True, null=True)),
                ("headache_extra_info", models.TextField(blank=True, null=True)),
                ("has_sorethroat", models.BooleanField(default=False)),
                ("sorethroat_severity", models.IntegerField(blank=True, null=True)),
                ("sorethroat_amt_of_days", models.IntegerField(blank=True, null=True)),
                ("sorethroat_extra_info", models.TextField(blank=True, null=True)),
                ("has_muscleaches", models.BooleanField(default=False)),
                ("muscleaches_severity", models.IntegerField(blank=True, null=True)),
                ("muscleaches_amt_of_days", models.IntegerField(blank=True, null=True)),
                ("muscleaches_extra_info", models.TextField(blank=True, null=True)),
                ("has_nausea", models.BooleanField(default=False)),
                ("nausea_severity", models.IntegerField(blank=True, null=True)),
                ("nausea_amt_of_days", models.IntegerField(blank=True, null=True)),
                ("nausea_extra_info", models.TextField(blank=True, null=True)),
                ("has_weightloss", models.BooleanField(default=False)),
                ("weightloss_amount", models.IntegerField(blank=True, null=True)),
                ("weightloss_extra_info", models.TextField(blank=True, null=True)),
                ("has_shortbreath", models.BooleanField(default=False)),
                ("shortbreath_severity", models.IntegerField(blank=True, null=True)),
                ("shortbreath_amt_of_days", models.IntegerField(blank=True, null=True)),
                ("shortbreath_extra_info", models.TextField(blank=True, null=True)),
                ("has_chills", models.BooleanField(default=False)),
                ("chills_severity", models.IntegerField(blank=True, null=True)),
                ("chills_amt_of_days", models.IntegerField(blank=True, null=True)),
                ("chills_extra_info", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
